-- Superseded by 009_runs.sql.
--
-- This migration once defined `execution_runs` and `execution_results`. Nothing ever
-- wrote to them: no Rust code referenced either table, and both were empty in every
-- database. They are removed here rather than migrated because there was nothing to
-- migrate, and 009 drops any copies left behind in databases that already ran this file.
--
-- Editing a past migration is safe in this project specifically: there is no migration
-- ledger — `run_migrations` re-executes every file on every startup and relies on
-- IF NOT EXISTS. Leaving the CREATEs here would mean 004 building two dead tables and
-- 009 dropping them again on every boot.
